sudo: required
services:
    - docker

before_install:
    -docker build -t arnas69/reacto-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arnas69/reacto-test npm test

after_success:
    - docker build -t arnas69/multi-client ./client
    - docker build -t arnas69/multi-nginx ./nginx
    - docker build -t arnas69/multi-server ./server
    - docker build -t arnas69/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push arnas69/multi-client
    - docker push arnas69/multi-nginx
    - docker push arnas69/multi-server
    - docker push arnas69/multi-worker